[theme]
primaryColor="#2563EB"    # Biru Tech (Tombol & Link)
backgroundColor="#FFFFFF" # Latar Putih Bersih
secondaryBackgroundColor="#F1F5F9" # Abu-abu sangat terang untuk Sidebar & Kotak
textColor="#1E293B"       # Teks Abu-abu Gelap Profesional
font="sans serif"
